package net.runelite.client.plugins.hoseaplugins.AutoRifts;

public enum AutoRiftsState {
    GET_CELLS,
    MOVE_TO_EAST_MINE,
    WAITING_FOR_GAME,
    ENTER_PORTAL,
    MINE_HUGE_GUARDIANS,
    MINE_LARGE_GUARDIANS,
    MINE_REGULAR_GUARDIANS,
    REPAIR_POUCH,
    CRAFTING_ESSENCE,
    CRAFT_ESSENCE,
    DEPOSIT_RUNES,
    CRAFT_RUNES,
    LEAVE_EAST_MINE,
    LEAVE_ALTAR,
    POWER_GUARDIAN,
    USE_CELL,
    ENTER_ALTAR,
    MINING,
    ENTER_GAME,
    GAME_BUSY,
    BREAK
}