package net.runelite.client.plugins.microbot.inventorysetups;

import com.google.common.collect.ImmutableMap;
import lombok.Getter;
import lombok.Setter;
import net.runelite.api.ItemID;

import java.awt.image.BufferedImage;
import java.util.Map;

import static net.runelite.api.ItemID.*;

/**
 * @author robbie, created on 19/09/2021 12:34
 */
public enum Bolts
{
	BRONZE(1, BRONZE_BOLTS),
	BLURITE(2, BLURITE_BOLTS),
	IRON(3, IRON_BOLTS),
	STEEL(4, STEEL_BOLTS),
	MITHRIL(5, MITHRIL_BOLTS),
	ADAMANT(6, ADAMANT_BOLTS),
	RUNITE(7, RUNITE_BOLTS),
	SILVER(8, SILVER_BOLTS),

	BRONZE_POISON1(9, BRONZE_BOLTS_P),
	BLURITE_POISON1(10, BLURITE_BOLTS_P),
	IRON_POISON1(11, IRON_BOLTS_P),
	STEEL_POISON1(12, STEEL_BOLTS_P),
	MITHRIL_POISON1(13, MITHRIL_BOLTS_P),
	ADAMANT_POISON1(14, ADAMANT_BOLTS_P),
	RUNITE_POISON1(15, RUNITE_BOLTS_P),
	SILVER_POISON1(16, SILVER_BOLTS_P),

	BRONZE_POISON2(17, BRONZE_BOLTS_P_6061),
	BLURITE_POISON2(18, BLURITE_BOLTS_P_9293),
	IRON_POISON2(19, IRON_BOLTS_P_9294),
	STEEL_POISON2(20, STEEL_BOLTS_P_9295),
	MITHRIL_POISON2(21, MITHRIL_BOLTS_P_9296),
	ADAMANT_POISON2(22, ADAMANT_BOLTS_P_9297),
	RUNITE_POISON2(23, RUNITE_BOLTS_P_9298),
	SILVER_POISON2(24, SILVER_BOLTS_P_9299),

	BRONZE_POISON3(25, BRONZE_BOLTS_P_6062),
	BLURITE_POISON3(26, BLURITE_BOLTS_P_9300),
	IRON_POISON3(27, IRON_BOLTS_P_9301),
	STEEL_POISON3(28, STEEL_BOLTS_P_9302),
	MITHRIL_POISON3(29, MITHRIL_BOLTS_P_9303),
	ADAMANT_POISON3(30, ADAMANT_BOLTS_P_9304),
	RUNITE_POISON3(31, RUNITE_BOLTS_P_9305),
	SILVER_POISON3(32, SILVER_BOLTS_P_9306),

	OPAL(33, OPAL_BOLTS),
	JADE(34, JADE_BOLTS),
	PEARL(35, PEARL_BOLTS),
	TOPAZ(36, TOPAZ_BOLTS),
	SAPPHIRE(37, SAPPHIRE_BOLTS),
	EMERALD(38, EMERALD_BOLTS),
	RUBY(39, RUBY_BOLTS),
	DIAMOND(40, DIAMOND_BOLTS),
	DRAGONSTONE(41, DRAGONSTONE_BOLTS),
	ONYX(42, ONYX_BOLTS),

	OPAL_E(43, OPAL_BOLTS_E),
	JADE_E(44, JADE_BOLTS_E),
	PEARL_E(45, PEARL_BOLTS_E),
	TOPAZ_E(46, TOPAZ_BOLTS_E),
	SAPPHIRE_E(47, SAPPHIRE_BOLTS_E),
	EMERALD_E(48, EMERALD_BOLTS_E),
	RUBY_E(49, RUBY_BOLTS_E),
	DIAMOND_E(50, DIAMOND_BOLTS_E),
	DRAGONSTONE_E(51, DRAGONSTONE_BOLTS_E),
	ONYX_E(52, ONYX_BOLTS_E),

	MITH_GRAPPLE(53, MITH_GRAPPLE_9419),
	BARBED(54, BARBED_BOLTS),
	BONE(55, BONE_BOLTS),
	BROAD(56, BROAD_BOLTS),
	AMETHYST_BROAD(57, AMETHYST_BROAD_BOLTS),

	DRAGON(58, DRAGON_BOLTS),
	DRAGON_POISON1(59, DRAGON_BOLTS_P),
	DRAGON_POISON2(60, DRAGON_BOLTS_P_21926),
	DRAGON_POISON3(61, DRAGON_BOLTS_P_21928),
	OPAL_DRAGON(62, OPAL_DRAGON_BOLTS),
	JADE_DRAGON(63, OPAL_DRAGON_BOLTS),
	PEARL_DRAGON(64, OPAL_DRAGON_BOLTS),
	TOPAZ_DRAGON(65, OPAL_DRAGON_BOLTS),
	SAPPHIRE_DRAGON(66, OPAL_DRAGON_BOLTS),
	EMERALD_DRAGON(67, OPAL_DRAGON_BOLTS),
	RUBY_DRAGON(68, OPAL_DRAGON_BOLTS),
	DIAMOND_DRAGON(69, OPAL_DRAGON_BOLTS),
	DRAGONSTONE_DRAGON(70, OPAL_DRAGON_BOLTS),
	ONYX_DRAGON(71, OPAL_DRAGON_BOLTS),

	OPAL_DRAGON_E(72, OPAL_DRAGON_BOLTS_E),
	JADE_DRAGON_E(73, JADE_DRAGON_BOLTS_E),
	PEARL_DRAGON_E(74, PEARL_DRAGON_BOLTS_E),
	TOPAZ_DRAGON_E(75, TOPAZ_DRAGON_BOLTS_E),
	SAPPHIRE_DRAGON_E(76, SAPPHIRE_DRAGON_BOLTS_E),
	EMERALD_DRAGON_E(77, EMERALD_DRAGON_BOLTS_E),
	RUBY_DRAGON_E(78, RUBY_DRAGON_BOLTS_E),
	DIAMOND_DRAGON_E(79, DIAMOND_DRAGON_BOLTS_E),
	DRAGONSTONE_DRAGON_E(80, DRAGONSTONE_DRAGON_BOLTS_E),
	ONYX_DRAGON_E(81, ONYX_DRAGON_BOLTS_E),

	BOLT_RACK(82, ItemID.BOLT_RACK);

	@Getter
	private final int id;
	@Getter
	private final int itemId;

	@Getter
	@Setter
	private BufferedImage image;

	private static final Map<Integer, Bolts> bolts;

	static
	{
		ImmutableMap.Builder<Integer, Bolts> builder = new ImmutableMap.Builder<>();
		for (Bolts bolt : values())
		{
			builder.put(bolt.getId(), bolt);
		}
		bolts = builder.build();
	}

	Bolts(int id, int itemId)
	{
		this.id = id;
		this.itemId = itemId;
	}

	public static Bolts getBolt(int varbit)
	{
		return bolts.get(varbit);
	}

}
