package net.runelite.client.plugins.microbot.bga.autoherblore.enums;

import net.runelite.api.gameval.ItemID;

public enum HerblorePotion {
    ATTACK(1, ItemID.GUAMVIAL, ItemID.EYE_OF_NEWT),
    ANTIPOISON(5, ItemID.MARRENTILLVIAL, ItemID.UNICORN_HORN_DUST),
    RELICYMS_BALM(8, ItemID.VIAL_WATER, ItemID.ROGUES_PURSE),
    STRENGTH(12, ItemID.TARROMINVIAL, ItemID.LIMPWURT_ROOT),
    RESTORE(22, ItemID.HARRALANDERVIAL, ItemID.RED_SPIDERS_EGGS),
    ENERGY(26, ItemID.HARRALANDERVIAL, ItemID.CHOCOLATE_DUST),
    DEFENCE(30, ItemID.RANARRVIAL, ItemID.WHITE_BERRIES),
    AGILITY(34, ItemID.TOADFLAXVIAL, ItemID.TOADS_LEGS),
    COMBAT(36, ItemID.HARRALANDERVIAL, ItemID.GROUND_DESERT_GOAT_HORN),
    PRAYER(38, ItemID.RANARRVIAL, ItemID.SNAPE_GRASS),
    SUPER_ATTACK(45, ItemID.IRITVIAL, ItemID.EYE_OF_NEWT),
    SUPER_ANTIPOISON(48, ItemID.IRITVIAL, ItemID.UNICORN_HORN_DUST),
    FISHING(50, ItemID.AVANTOEVIAL, ItemID.SNAPE_GRASS),
    SUPER_ENERGY(52, ItemID.AVANTOEVIAL, ItemID.MORTMYREMUSHROOM),
    HUNTER(53, ItemID.AVANTOEVIAL, ItemID.HUNTINGBEAST_SABRETEETH_DUST),
    SUPER_STRENGTH(55, ItemID.KWUARMVIAL, ItemID.LIMPWURT_ROOT),
    MAGIC_ESSENCE(57, ItemID.FAIRYTALE2_STARFLOWERVIAL, ItemID.FAIRYTALE2_GROUND_GORAK_CLAWS),
    WEAPON_POISON(60, ItemID.KWUARMVIAL, ItemID.DRAGON_SCALE_DUST),
    SUPER_RESTORE(63, ItemID.SNAPDRAGONVIAL, ItemID.RED_SPIDERS_EGGS),
    SANFEW_SERUM(65, ItemID._4DOSE2RESTORE, ItemID.UNICORN_HORN_DUST),
    SUPER_DEFENCE(66, ItemID.CADANTINEVIAL, ItemID.WHITE_BERRIES),
    ANTIDOTE_PLUS(68, ItemID.VIAL_COCONUT_MILK, ItemID.TOADFLAX),
    ANTIFIRE(69, ItemID.LANTADYMEVIAL, ItemID.DRAGON_SCALE_DUST),
    RANGING(72, ItemID.DWARFWEEDVIAL, ItemID.WINE_OF_ZAMORAK),
    WEAPON_POISON_PLUS(73, ItemID.VIAL_COCONUT_MILK, ItemID.CACTUS_SPINE),
    MAGIC(76, ItemID.LANTADYMEVIAL, ItemID.CACTUS_POTATO),
    STAMINA(77, ItemID._4DOSE2ENERGY, ItemID.AMYLASE),
    ZAMORAK_BREW(78, ItemID.TORSTOLVIAL, ItemID.JANGERBERRIES),
    ANTIDOTE_PLUS_PLUS(79, ItemID.VIAL_COCONUT_MILK, ItemID.IRIT_LEAF),
    BASTION(80, ItemID.CADANTINE_BLOODVIAL, ItemID.WINE_OF_ZAMORAK),
    BATTLEMAGE(80, ItemID.CADANTINE_BLOODVIAL, ItemID.CACTUS_POTATO),
    SARADOMIN_BREW(81, ItemID.TOADFLAXVIAL, ItemID.CRUSHED_BIRD_NEST),
    WEAPON_POISON_PLUS_PLUS(82, ItemID.VIAL_COCONUT_MILK, ItemID.NIGHTSHADE),
    EXTENDED_ANTIFIRE(84, ItemID._4DOSE1ANTIDRAGON, ItemID.LAVA_SHARD),
    DIVINE_BASTION(86, ItemID._4DOSEBASTION, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    DIVINE_BATTLEMAGE(86, ItemID._4DOSEBATTLEMAGE, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    ANTI_VENOM(87, ItemID.ANTIDOTE__4, ItemID.SNAKEBOSS_SCALE),
    SUPER_COMBAT(90, ItemID.TORSTOL, ItemID._4DOSE2ATTACK),
    SUPER_ANTIFIRE(92, ItemID._4DOSE1ANTIDRAGON, ItemID.CRUSHED_DRAGON_BONES),
    ANTI_VENOM_PLUS(94, ItemID.ANTIVENOM4, ItemID.TORSTOL),
    EXTENDED_ANTI_VENOM_PLUS(94, ItemID.ANTIVENOM_4, ItemID.ARAXYTE_VENOM_SACK),
    DIVINE_SUPER_ATTACK(70, ItemID._4DOSE2ATTACK, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    DIVINE_SUPER_STRENGTH(70, ItemID._4DOSE2STRENGTH, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    DIVINE_SUPER_DEFENCE(70, ItemID._4DOSE2DEFENSE, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    DIVINE_RANGING(74, ItemID._4DOSERANGERSPOTION, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    DIVINE_MAGIC(74, ItemID._4DOSE1MAGIC, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    DIVINE_SUPER_COMBAT(97, ItemID._4DOSE2COMBAT, ItemID.PRIF_CRYSTAL_SHARD_CRUSHED),
    EXTENDED_SUPER_ANTIFIRE(98, ItemID._4DOSE3ANTIDRAGON, ItemID.LAVA_SHARD);

    public final int level;
    public final int unfinished;
    public final int secondary;

    HerblorePotion(int level, int unfinished, int secondary) {
        this.level = level;
        this.unfinished = unfinished;
        this.secondary = secondary;
    }
}
