package net.runelite.client.plugins.hoseaplugins.lucidtobprayers;

public enum EventType
{
    ANIMATION_CHANGED, NPC_SPAWNED, NPC_DESPAWNED, NPC_CHANGED, PROJECTILE_SPAWNED,
    GRAPHICS_CREATED, GAME_OBJECT_SPAWNED, OTHER_INTERACT_YOU, YOU_INTERACT_OTHER, ITEM_EQUIPPED
}
